[package]
name = "ld48-repsi0-descent"
version = "0.1.0"
authors = ["Repsi0 <repeerc710@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.1"
quad-snd = "0.1.0-alpha.1"
rand = "0.8.3"